/**
 * Frozen compatibility surface for Paw's versioned V15 integration.
 *
 * New hosts should import the small default entrypoint. Serialized schema
 * revisions remain explicit even when public TypeScript names do not carry a
 * V1/V2/V3 suffix.
 */
export {
  createMemoryEvidenceAnswerPolicyV1,
  PAW_MEMORY_EVIDENCE_ANSWER_POLICY_VERSION_V1,
  type MemoryEvidenceAnswerOperationV1,
  type MemoryEvidenceAnswerPolicyV1,
} from "./evidence-answer-policy.js";
export {
  createEvidenceFirstMemoryContextResolverV1,
  PAW_MEMORY_EVIDENCE_ANSWER_CONTRACT_VERSION_V1,
  projectEvidenceFirstMemoryAnswerContractV1,
  projectEvidenceFirstMemoryContextPacketV1,
  type MemoryEvidenceAnswerContractV1,
} from "./evidence-context-adapter.js";
export {
  PAW_MEMORY_PRODUCT_EVIDENCE_INDEX_VERSION_V1,
  createProductMemoryEvidenceIndexV1,
  evidenceSourceIdV1,
} from "./evidence-index-adapter.js";
export {
  DEFAULT_MEMORY_SOURCE_LOCAL_EVIDENCE_BUDGET_V1,
  PAW_MEMORY_SOURCE_LOCAL_EVIDENCE_LOCATOR_PORT_VERSION_V1,
  PAW_MEMORY_SOURCE_LOCAL_LEAF_ELIGIBILITY_VERSION_V2,
  evaluateMemorySourceLocalLeafEligibilityV2,
  isMemorySourceLocalEvidenceEligibleV1,
  isMemorySourceLocalEvidenceRouteEligibleV2,
  hasMemorySourceLocalDialogueCertificateV1,
  hydrateMemorySourceLocalEvidenceResultV1,
  memorySourceLocalAnchorKindsV1,
  memorySourceLocalEvidenceCacheKeyV1,
  validateMemoryDialoguePredecessorVerificationV1,
  validateMemorySourceLocalEvidenceResultV1,
  type MemoryDialoguePredecessorProofV1,
  type MemoryDialoguePredecessorTargetV1,
  type MemoryDialoguePredecessorVerificationRequestV1,
  type MemoryDialoguePredecessorVerificationResultV1,
  type MemoryDialoguePredecessorVerifierV1,
  type MemorySourceLocalEvidenceBudgetV1,
  type MemorySourceLocalAnchorKindV1,
  type MemorySourceLocalEvidenceHitV1,
  type MemorySourceLocalEvidenceHydratorV1,
  type MemorySourceLocalHydratedEvidenceV1,
  type MemorySourceLocalEvidenceLocatorV1,
  type MemorySourceLocalEvidenceRequestV1,
  type MemorySourceLocalEvidenceResultV1,
  type MemorySourceLocalEvidenceTelemetryV1,
  type MemorySourceLocalLeafEligibilityReasonV2,
  type MemorySourceLocalLeafEligibilityV2,
  type MemorySourceLocalLeafExecutionReportV2,
  type MemorySourceLocalizationReportV1,
  type MemorySourceLocalizationStatusV1,
} from "./source-local-evidence-locator.js";
export {
  PAW_MEMORY_EVIDENCE_CLOSURE_AUDITOR_VERSION_V1,
  buildMemoryEvidenceClosureAuditRequestV1,
  createJsonMemoryEvidenceClosureAuditorV1,
  parseMemoryEvidenceClosureAuditV1,
  validateMemoryEvidenceClosureAuditBoundaryV1,
  type MemoryEvidenceClosureAuditInputV1,
  type MemoryEvidenceClosureAuditV1,
  type MemoryEvidenceClosureAuditorV1,
  type MemoryEvidenceClosureVerdictV1,
} from "./evidence-closure-auditor.js";
export {
  PAW_MEMORY_EVIDENCE_OBLIGATION_VERSION_V1,
  compileMemoryEvidenceObligationShapeV1,
  memoryEvidenceQueryHasMultipleObligationsV1,
  validateMemoryEvidenceObligationsV1,
  type MemoryEvidenceObligationReasonV1,
  type MemoryEvidenceObligationShapeV1,
} from "./evidence-obligation.js";
export {
  PAW_MEMORY_EVIDENCE_QUERY_PLANNER_VERSION_V3,
  PAW_MEMORY_EVIDENCE_TEMPORAL_COMPATIBILITY_VERSION_V1,
  PAW_MEMORY_EVIDENCE_TEMPORAL_CONSTRAINT_VERSION_V1,
  bindMemoryEvidenceTemporalConstraintV1,
  buildMemoryEvidenceQueryPlanRequestV3,
  classifyMemoryEvidenceIntentBoundaryV1,
  classifyMemoryEvidenceQueryV3,
  classifyMemoryQueryAnswerProvenanceFeaturesV1,
  compileMemoryEvidenceTemporalConstraintV1,
  compileMemoryQueryAnswerOriginV1,
  createJsonMemoryEvidenceQueryPlannerV3,
  memoryQueryAnswerOriginAllowsLateBindingV1,
  memoryEvidenceLeafTemporalModeAllowedV1,
  needsCertifiedAssistantDialogueCandidateV1,
  needsMemoryEvidenceRoleResolutionV1,
  parseMemoryEvidenceQueryPlanV3,
  PAW_MEMORY_QUERY_ANSWER_ORIGIN_AUTHORIZATION_VERSION_V1,
  PAW_MEMORY_QUERY_ANSWER_ORIGIN_VERSION_V1,
  validateMemoryEvidenceQueryPlanOriginV1,
  validateMemoryEvidenceTemporalConstraintV1,
  validateMemoryQueryAnswerOriginAuthorizationV1,
  type MemoryEvidenceAnswerShapeV3,
  type MemoryEvidenceBoundTemporalConstraintV1,
  type MemoryEvidenceIntentBoundaryV1,
  type MemoryEvidenceQueryIntentV3,
  type MemoryEvidenceQueryPlanV3,
  type MemoryEvidenceQueryPlannerV3,
  type MemoryEvidenceRequirementV3,
  type MemoryEvidenceRoleConstraintV3,
  type MemoryEvidenceTemporalModeV3,
  type MemoryEvidenceTemporalConstraintV1,
  type MemoryQueryAnswerOriginAuthorizationV1,
  type MemoryQueryAnswerOriginKindV1,
  type MemoryQueryAnswerOriginMaterializationModeV1,
  type MemoryQueryAnswerOriginV1,
  type MemoryQueryAnswerProvenanceFeaturesV1,
} from "./evidence-query-planner.js";
export {
  PAW_MEMORY_EVIDENCE_RESOLVER_VERSION_V1,
  createMemoryEvidenceResolverV1,
  type MemoryEvidenceIndexSearchResultV1,
  type MemoryEvidenceIndexV1,
  type MemoryEvidenceResolutionV1,
  type MemoryEvidenceClosureModeV1,
} from "./evidence-resolver.js";
export {
  PAW_MEMORY_EVIDENCE_SUPPORT_SELECTOR_VERSION_V1,
  buildMemoryEvidenceSupportSelectionRequestV1,
  createJsonMemoryEvidenceSupportSelectorV1,
  parseMemoryEvidenceSupportGroupedSelectionV1,
  parseMemoryEvidenceSupportSelectionV1,
  projectMemoryEvidenceSupportSelectionInputV1,
  type MemoryEvidenceSupportSelectionV1,
  type MemoryEvidenceSupportGroupedSelectionV1,
  type MemoryEvidenceSupportSelectionGroupDescriptorV1,
  type MemoryEvidenceSupportSelectionGroupResultV1,
  type MemoryEvidenceSupportSelectionInputV1,
  type MemoryEvidenceSupportSelectorV1,
  type MemoryEvidenceTriageAssessmentV1,
} from "./evidence-support-selector.js";
export {
  buildMemoryConversationTurnBundleV1,
  buildMemoryEvidenceNotebookV1,
  isAssistantMemoryQueryV1,
  PAW_MEMORY_CONVERSATION_BUNDLE_POLICY_VERSION_V1,
  PAW_MEMORY_EVIDENCE_CANDIDATE_FUSION_VERSION_V2,
  PAW_MEMORY_EVIDENCE_FIRST_POLICY_VERSION_V1,
  PAW_MEMORY_EVIDENCE_NOTEBOOK_POLICY_VERSION_V1,
  memoryEvidenceOrdinalAnchorScoreV1,
  memoryEvidenceSupportScoreV1,
  projectMemoryEvidenceExcerptV1,
  rankMemoryEvidenceCandidatesV2,
  rankMemoryEvidenceSourcesV1,
  selectRankedMemoryConversationBundlesV1,
  type MemoryConversationTurnBundleV1,
  type MemoryConversationTurnKindV1,
  type MemoryConversationTurnV1,
  type MemoryEvidenceAuthorityV2,
  type MemoryEvidenceCandidateFusionV2,
  type MemoryEvidenceCandidateRankListV2,
  type MemoryEvidenceCandidateV2,
  type MemoryEvidenceChannelV1,
  type MemoryEvidenceKindV2,
  type MemoryEvidenceNotebookHitV1,
  type MemoryEvidenceNotebookRequirementV1,
  type MemoryEvidenceNotebookV1,
  type MemoryEvidenceSourceFusionV1,
  type MemoryEvidenceSourceRankListV1,
  type RankedMemoryEvidenceCandidateV2,
  type RankedMemoryEvidenceSourceV1,
  type RankedMemoryEvidenceSourceV2,
  type SelectedMemoryConversationBundlesV1,
} from "./evidence-first.js";
export {
  PAW_MEMORY_STATE_REDUCER_VERSION_V1,
  compareStateObservationV1,
  inferMemoryStateSemanticsV1,
  resolveMemoryStateObservationsV1,
  type MemoryStateEpistemicStatusV1,
  type MemoryStateKindV1,
  type MemoryStateObservationV1,
  type MemoryStateResolutionV1,
  type MemoryStateValueQualifierV1,
} from "./state-observation.js";
export {
  createInMemoryEvidenceStoreV1,
  type InMemoryCardInputV1,
  type InMemoryEvidenceInputV1,
  type InMemoryEvidenceStoreV1,
} from "./in-memory-store.js";
export type {
  MemoryProductArchiveV1,
  MemoryProductCardV1,
  MemoryProductProfileV1,
  MemoryProductProviderV1,
  MemoryProductRawEvidenceV1,
  MemoryProductScopeV1,
} from "./product-ports.js";
export type { MemoryWriterModelV1 } from "./model-port.js";
export {
  PAW_MEMORY_CONTEXT_RESOLVER_VERSION_V1,
  type MemoryContextResolverV1,
  type MemoryRawEvidenceSpanV1,
  type MemoryResolvedContextEvidenceV1,
  type MemoryResolvedContextPacketV1,
  type MemoryResolvedContextTopicV1,
  type MemoryResolvedTopicStateV1,
} from "./context-contract.js";
