/**
 * @paw/protocol contains implementation-free package-boundary DTOs.
 *
 * During WP1a it is an internal compatibility bridge, not a frozen public SDK.
 * It must remain free of Paw package and runtime dependencies.
 */

export type {
  MemoryKind,
  MemoryMetadata,
  MemoryPriority,
  LegacyMemoryRecordV1,
  MemoryScope,
  MemorySource,
  MemoryStatus,
  LegacyProjectMemoryV1,
  TaskProfile,
} from "./memory.js";

export {
  assertRunJournalEnvelopeCanFollowV1,
  assertRunJournalEnvelopeV1,
  assertModelResponseV1,
  assertToolObservationV1,
  assertTaskCheckpointV1,
  CRASH_RECOVERY_INCOMPLETE_REASONS_V1,
  COMPLETION_REVIEW_POLICY_VERSION_V1,
  MEMORY_ATOM_PROPOSAL_SCHEMA_VERSION_V1,
  MEMORY_EVIDENCE_COVERAGE_POLICY_VERSION_V1,
  MEMORY_PERSONA_PROJECTION_POLICY_VERSION_V1,
  MEMORY_RAW_EVIDENCE_POLICY_VERSION_V1,
  MEMORY_RETRIEVAL_POLICY_VERSION_V1,
  MEMORY_TOPIC_ORGANIZATION_POLICY_VERSION_V1,
  MEMORY_TOPIC_EVIDENCE_POLICY_VERSION_V1,
  MEMORY_TOPIC_PROPOSAL_SCHEMA_VERSION_V1,
  MEMORY_WRITE_POLICY_VERSION_V1,
  isCrashRecoveryIncompleteActionV1,
  isCrashRecoveryIncompleteReasonV1,
  isModelResponseV1,
  isRunJournalEnvelopeV1,
  isToolObservationV1,
  isTaskCheckpointV1,
  MODEL_RESPONSE_SCHEMA_VERSION_V1,
  parseModelResponseV1,
  parseRunJournalEnvelopeV1,
  parseRunJournalPrefixV1,
  parseToolObservationV1,
  parseTaskCheckpointV1,
  RUN_JOURNAL_SCHEMA_VERSION_V1,
  TOOL_OBSERVATION_SCHEMA_VERSION_V1,
  TASK_CHECKPOINT_SCHEMA_VERSION_V1,
  WORK_SEGMENT_POLICY_VERSION_V1,
  type AbortDecisionActionV1,
  type AbortRequestedFactV1,
  type AttemptStartedFactV1,
  type CompleteDecisionActionV1,
  type CompletionReviewClaimedFactV1,
  type CompletionReviewSettledFactV1,
  type CompletionReviewTriggerV1,
  type CompletionReviewVerdictV1,
  type ContextCheckpointRecordedFactV1,
  type ContextCheckpointDistillationClaimedFactV1,
  type ContextCheckpointDistillationSettledFactV1,
  type ControlDecisionActionV1,
  type ContinueDecisionActionV1,
  type DerivedDecisionV1,
  type DurableJsonPayloadV1,
  type FailedDecisionActionV1,
  type IncompleteDecisionActionV1,
  type InputAcceptedFactV1,
  type InputPromotedFactV1,
  type InputAttachmentV1,
  type InputFactV1,
  type JsonPrimitive,
  type JsonValue,
  type MemoryCardV1,
  type MemoryAtomActionV1,
  type MemoryAtomKindV1,
  type MemoryAtomProposalV1,
  type MemoryCandidateStagedFactV1,
  type MemoryEvidenceCoverageItemV1,
  type MemoryEvidenceCoverageSettledFactV1,
  type MemoryEvidenceRequirementV1,
  type MemoryPersonaClaimV1,
  type MemoryPersonaProjectionSettledFactV1,
  type MemoryRawEvidenceSettledFactV1,
  type MemoryRawEvidenceSpanV1,
  type MemoryRetrievalSettledFactV1,
  type MemorySourceRefV1,
  type MemoryTopicCandidateStagedFactV1,
  type MemoryTopicEvidenceSettledFactV1,
  type MemoryTopicEvidenceStateV1,
  type MemoryTopicFamilyV1,
  type MemoryTopicIndexEntryV1,
  type MemoryTopicMemberProposalV1,
  type MemoryTopicOrganizationClaimedFactV1,
  type MemoryTopicOrganizationSettledFactV1,
  type MemoryTopicProposalV1,
  type MemoryWriteClaimedFactV1,
  type MemoryWriteSettledFactV1,
  type ModelDispatchRecordedFactV1,
  type ModelSettledFactV1,
  type ModelResponseToolCallV1,
  type ModelResponseUsageV1,
  type ModelResponseV1,
  type ModelSettlementStatusV1,
  type PolicyRequestRecordedFactV1,
  type RunJournalEnvelopeV1,
  type RunJournalRecordV1,
  type RuntimeFailedFactV1,
  type RuntimeActivityStartedFactV1,
  type RuntimeActivitySettledFactV1,
  type ToolCallObservedFactV1,
  type ToolDispatchRecordedFactV1,
  type ToolEffectCheckpointAllocatedFactV1,
  type ToolPermissionResolvedFactV1,
  type ToolSettledFactV1,
  type ToolSettlementStatusV1,
  type ToolObservationV1,
  type TaskCheckpointItemV1,
  type TaskCheckpointDistillationStatusV1,
  type TaskCheckpointV1,
  type WaitDecisionActionV1,
  type WorkSegmentStartedFactV1,
} from "./run-journal.js";
